[tool.flakeheaven]
baseline = ".flakehell_baseline"
format = "grouped"
show_source = true
statistics = false
doctests = false
enable_extensions = "G"

exclude = ["tests"]

accept_encodings = "utf-8"
max_line_length = 99

# complexity; see https://wemake-python-stylegui.de/en/latest/pages/usage/violations/complexity.html#complexity
max_jones_score = 12
max_cognitive_score = 208 # extremely high
max_line_complexity = 21 # high
max_imports = 49 # very high
max_module_members = 14 # very high
max_imported_names = 62 # very high
max_module_expressions = 47 # very high
max_function_expressions = 8 # high
max_local_variables = 15 # very high
max_string_usages = 24 # extremely high
max_arguments = 11 # very high
max_returns = 11 # very high
max_expressions = 26 # very high
max_methods = 30 # very high
max_base_classes = 3
max_decorators = 5
max_awaits = 5
max_asserts = 5
max_try_body_length = 17 # very high
max_attributes = 12 # very high
max_cognitive_average = 34 # very high
max_call_level = 3
max_annotation_complexity = 4
max_import_from_members = 12
max_tuple_unpack_length = 4

[tool.flakeheaven.plugins]
"flake8-annotations" = ["-*", "+ANN001", "+ANN2??", "+ANN301"]
"wemake-python-styleguide" = ["-*", "+WPS2??", "-WPS220", "-WPS223", "-WPS222"] # WPS2?? is complexity; 220 is deep nesting; 223 is elifs; 222 is logic
"flake8-bandit" = ["+*", "-S404", "-S603", "-E902"]
