// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: inbs_sb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	INBSSBService_Ping_FullMethodName = "/inbs.INBSSBService/Ping"
)

// INBSSBServiceClient is the client API for INBSSBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type INBSSBServiceClient interface {
	// Bi-directional streaming method
	Ping(ctx context.Context, opts ...grpc.CallOption) (INBSSBService_PingClient, error)
}

type iNBSSBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewINBSSBServiceClient(cc grpc.ClientConnInterface) INBSSBServiceClient {
	return &iNBSSBServiceClient{cc}
}

func (c *iNBSSBServiceClient) Ping(ctx context.Context, opts ...grpc.CallOption) (INBSSBService_PingClient, error) {
	stream, err := c.cc.NewStream(ctx, &INBSSBService_ServiceDesc.Streams[0], INBSSBService_Ping_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &iNBSSBServicePingClient{stream}
	return x, nil
}

type INBSSBService_PingClient interface {
	Send(*PingResponse) error
	Recv() (*PingRequest, error)
	grpc.ClientStream
}

type iNBSSBServicePingClient struct {
	grpc.ClientStream
}

func (x *iNBSSBServicePingClient) Send(m *PingResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *iNBSSBServicePingClient) Recv() (*PingRequest, error) {
	m := new(PingRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// INBSSBServiceServer is the server API for INBSSBService service.
// All implementations must embed UnimplementedINBSSBServiceServer
// for forward compatibility
type INBSSBServiceServer interface {
	// Bi-directional streaming method
	Ping(INBSSBService_PingServer) error
	mustEmbedUnimplementedINBSSBServiceServer()
}

// UnimplementedINBSSBServiceServer must be embedded to have forward compatible implementations.
type UnimplementedINBSSBServiceServer struct {
}

func (UnimplementedINBSSBServiceServer) Ping(INBSSBService_PingServer) error {
	return status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedINBSSBServiceServer) mustEmbedUnimplementedINBSSBServiceServer() {}

// UnsafeINBSSBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to INBSSBServiceServer will
// result in compilation errors.
type UnsafeINBSSBServiceServer interface {
	mustEmbedUnimplementedINBSSBServiceServer()
}

func RegisterINBSSBServiceServer(s grpc.ServiceRegistrar, srv INBSSBServiceServer) {
	s.RegisterService(&INBSSBService_ServiceDesc, srv)
}

func _INBSSBService_Ping_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(INBSSBServiceServer).Ping(&iNBSSBServicePingServer{stream})
}

type INBSSBService_PingServer interface {
	Send(*PingRequest) error
	Recv() (*PingResponse, error)
	grpc.ServerStream
}

type iNBSSBServicePingServer struct {
	grpc.ServerStream
}

func (x *iNBSSBServicePingServer) Send(m *PingRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *iNBSSBServicePingServer) Recv() (*PingResponse, error) {
	m := new(PingResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// INBSSBService_ServiceDesc is the grpc.ServiceDesc for INBSSBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var INBSSBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inbs.INBSSBService",
	HandlerType: (*INBSSBServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ping",
			Handler:       _INBSSBService_Ping_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "inbs_sb.proto",
}
