// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: inbs/v1/inbs_sb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	INBSSBService_HandleINBMCommand_FullMethodName = "/inbs.v1.INBSSBService/HandleINBMCommand"
	INBSSBService_SendNodeUpdate_FullMethodName    = "/inbs.v1.INBSSBService/SendNodeUpdate"
)

// INBSSBServiceClient is the client API for INBSSBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type INBSSBServiceClient interface {
	// Bi-directional streaming method
	HandleINBMCommand(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HandleINBMCommandResponse, HandleINBMCommandRequest], error)
	// Used to send any kind of node status update
	SendNodeUpdate(ctx context.Context, in *SendNodeUpdateRequest, opts ...grpc.CallOption) (*SendNodeUpdateResponse, error)
}

type iNBSSBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewINBSSBServiceClient(cc grpc.ClientConnInterface) INBSSBServiceClient {
	return &iNBSSBServiceClient{cc}
}

func (c *iNBSSBServiceClient) HandleINBMCommand(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HandleINBMCommandResponse, HandleINBMCommandRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &INBSSBService_ServiceDesc.Streams[0], INBSSBService_HandleINBMCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HandleINBMCommandResponse, HandleINBMCommandRequest]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type INBSSBService_HandleINBMCommandClient = grpc.BidiStreamingClient[HandleINBMCommandResponse, HandleINBMCommandRequest]

func (c *iNBSSBServiceClient) SendNodeUpdate(ctx context.Context, in *SendNodeUpdateRequest, opts ...grpc.CallOption) (*SendNodeUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendNodeUpdateResponse)
	err := c.cc.Invoke(ctx, INBSSBService_SendNodeUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// INBSSBServiceServer is the server API for INBSSBService service.
// All implementations must embed UnimplementedINBSSBServiceServer
// for forward compatibility.
type INBSSBServiceServer interface {
	// Bi-directional streaming method
	HandleINBMCommand(grpc.BidiStreamingServer[HandleINBMCommandResponse, HandleINBMCommandRequest]) error
	// Used to send any kind of node status update
	SendNodeUpdate(context.Context, *SendNodeUpdateRequest) (*SendNodeUpdateResponse, error)
	mustEmbedUnimplementedINBSSBServiceServer()
}

// UnimplementedINBSSBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedINBSSBServiceServer struct{}

func (UnimplementedINBSSBServiceServer) HandleINBMCommand(grpc.BidiStreamingServer[HandleINBMCommandResponse, HandleINBMCommandRequest]) error {
	return status.Errorf(codes.Unimplemented, "method HandleINBMCommand not implemented")
}
func (UnimplementedINBSSBServiceServer) SendNodeUpdate(context.Context, *SendNodeUpdateRequest) (*SendNodeUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNodeUpdate not implemented")
}
func (UnimplementedINBSSBServiceServer) mustEmbedUnimplementedINBSSBServiceServer() {}
func (UnimplementedINBSSBServiceServer) testEmbeddedByValue()                       {}

// UnsafeINBSSBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to INBSSBServiceServer will
// result in compilation errors.
type UnsafeINBSSBServiceServer interface {
	mustEmbedUnimplementedINBSSBServiceServer()
}

func RegisterINBSSBServiceServer(s grpc.ServiceRegistrar, srv INBSSBServiceServer) {
	// If the following call pancis, it indicates UnimplementedINBSSBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&INBSSBService_ServiceDesc, srv)
}

func _INBSSBService_HandleINBMCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(INBSSBServiceServer).HandleINBMCommand(&grpc.GenericServerStream[HandleINBMCommandResponse, HandleINBMCommandRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type INBSSBService_HandleINBMCommandServer = grpc.BidiStreamingServer[HandleINBMCommandResponse, HandleINBMCommandRequest]

func _INBSSBService_SendNodeUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNodeUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(INBSSBServiceServer).SendNodeUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: INBSSBService_SendNodeUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(INBSSBServiceServer).SendNodeUpdate(ctx, req.(*SendNodeUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// INBSSBService_ServiceDesc is the grpc.ServiceDesc for INBSSBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var INBSSBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inbs.v1.INBSSBService",
	HandlerType: (*INBSSBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendNodeUpdate",
			Handler:    _INBSSBService_SendNodeUpdate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HandleINBMCommand",
			Handler:       _INBSSBService_HandleINBMCommand_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "inbs/v1/inbs_sb.proto",
}
