#!/bin/sh

set -euxo pipefail

function run_FOTA() {
  # Current WA for SOTA/FOTA together:
  # 1. Send FIP through SOTA request. It will fail to perform SOTA and the file is located
  #    at /var/cache/manageability/repository-tool/.
  # 2. After that, send mender file and perform SOTA.
  # 3. After system reboot, this script will check if there is SOTA perform previously. If SOTA performed previously and
  #    fip binary exist. It will call movisoc tool to flash the fip and reboot.
  if [  -f /etc/dispatcher_state ]; then
    if [  -f /var/cache/manageability/repository-tool/fip* ]; then
          echo "Found FIP."
          movisoc-fwu -a /var/cache/manageability/repository-tool/fip*
          echo "Update FIP complete. Remove FIP."
          rm /var/cache/manageability/repository-tool/fip*
          echo "Commit mender."
          mender -commit
          reboot
    fi
  fi
}

if [  -f /etc/intel-manageability/secret/.provisioned ]; then
        echo "Manageability already provisioned."
        exit 0
fi

if [ -f /etc/intel-manageability/AUTO_ENABLED ]; then
	echo "Already autoenabled."
	exit 0
fi

KMB_PCIE_EP_STATUS="/proc/device-tree/soc/pcie_ep@37000000/status"
THB_PCIE_EP_STATUS="/proc/device-tree/soc/pcie_ep@82000000/status"

if [ -f $KMB_PCIE_EP_STATUS ]; then
  PCIE_EP_STATUS=$KMB_PCIE_EP_STATUS
elif [ -f $THB_PCIE_EP_STATUS ]; then
  PCIE_EP_STATUS=$THB_PCIE_EP_STATUS
else
  PCIE_EP_STATUS=""
fi

# Status is okay if it is in HDDL mode.
if [ ! $PCIE_EP_STATUS == "" ]; then
    IS_HDDL=$(cat $PCIE_EP_STATUS | tr -d '\0')
    echo $IS_HDDL
    if [ $IS_HDDL == "okay" ]; then
        echo HDDL mode enabled.
        run_FOTA
        sed -i 's/<networkCheck>true<\/networkCheck>/<networkCheck>false<\/networkCheck>/' /etc/intel_manageability.conf
        # Temporary disable TPM until TPM issue is resolved.
        mqtt-remove-keys || true
        NO_DOCKER=1 NO_CLOUD=1 PROVISION_TPM=disable NO_OTA_CERT=1 /usr/bin/provision-tc
        systemctl enable inbm-node.service
	touch /etc/intel-manageability/AUTO_ENABLED  # This is run AFTER node is enabled (but not started) and provision-tc succeeds, in case there is an error starting node.

        # Finally, we start inbm-node.service.
        # TODO: BC needs a provision-bc script. This is temporary:
        if [ -f /usr/bin/inbm-node ] ; then
            systemctl start inbm-node.service
        fi
    fi
fi
