# -*- mode: ruby -*-
# vi: set ft=ruby :

# Set proxy from environment
proxy = ENV['http_proxy'] || ENV['https_proxy'] 
no_proxy = ENV['no_proxy']

Vagrant.configure("2") do |config|
  config.vm.box = "peru/windows-10-enterprise-x64-eval"
  config.vm.box_version = "20230601.01"

  # Configure the proxy for Vagrant
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = proxy
    config.proxy.https    = proxy
    config.proxy.no_proxy = "127.0.0.1"
  end
  
  config.vm.provider "virtualbox" do |v|
    config.vm.synced_folder "inb-files", "/inb-files"
    v.memory = 8192
    v.cpus = 4
  end

  config.vm.provision "shell", inline: <<-SHELL
    New-Item -Path "C:\\ucc\\client_id" -ItemType File -Force
    Set-Content -Path "C:\\ucc\\client_id" -Value "12345678abcd"

    New-Item -Path "C:\\ucc\\server_id" -ItemType File -Force
    Set-Content -Path "C:\\ucc\\server_id" -Value "123"
  SHELL
  config.vm.provision "shell", path: "inb-files/intel-manageability/uninstall.ps1", env: {"UCC_MODE" => "true"}
  config.vm.provision "shell", path: "inb-files/intel-manageability/install.ps1", env: {"UCC_MODE" => "true"}
  config.vm.provision "shell", path: "uccmosquitto.ps1"
  config.vm.provision "file", source: "adapter.cfg", destination: "/intel-manageability/inbm/etc/secret/cloudadapter-agent/adapter.cfg"
  config.vm.provision "shell", path: "inb-files/intel-manageability/provision.ps1", env: {"NO_CLOUD" => "true"}

  config.vm.provision "shell", path: "python.ps1"
  config.vm.provision "shell", inline: <<-SHELL
    net start uccmosquitto
    net start inbm-cloudadapter
    pip install paho-mqtt==1.6.1
    python c:\\inb-files\\UCC_FLOW_TEST.py
  SHELL
  
  config.vm.provision "shell", run: "always", inline: <<-SHELL
    Write-Output "Contents of manageability.log:"
    Get-Content "C:\\intel-manageability\\inbm\\var\\manageability.log"
  SHELL
end
