services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - inbm_network
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  cloudadapter:
    build:
      context: ..
      dockerfile: docker/Dockerfile.cloudadapter
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - USE_TLS=False
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY}
    volumes:
      - ./adapter.cfg:/etc/intel-manageability/secret/cloudadapter-agent/adapter.cfg
    networks:
      - inbm_network

  telemetry:
    build:
      context: ..
      dockerfile: docker/Dockerfile.telemetry
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - USE_TLS=False
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY}
    networks:
      - inbm_network

networks:
  inbm_network:
    driver: bridge
