#!/bin/sh

set -euxo pipefail

# Check node in flashless environment
if ! grep -q root /proc/cmdline ; then
    echo Flashless system detected.
    if [ -f /usr/bin/inbm-node ] ; then
        systemctl enable --now inbm-node.service
    fi
fi
