[tool.flakehell]
baseline = ".flakehell_baseline"
format = "grouped"
show_source = true
statistics = false
doctests = false
enable_extensions = "G"

exclude = ["tests",
    "vision/tests",
    "inbm_lib/tests",
    "inbm_vision_lib/tests",
    "inbm_common_lib/tests",
    "node/tests",
    "mqttclient/tests"]

accept_encodings = "utf-8"
max_line_length = 99

max_jones_score = 6
max_cognitive_score = 39 # 12
max_try_body_length = 13 # 1
max_arguments = 10 # 5
max_methods = 31 # 7
max_local_variables = 9 # 5
max_expressions = 15 # 9
max_returns = 5 # 5
max_function_expressions = 4 # 4
max_line_complexity = 21 # 14
max_module_expressions = 49 # 7
max_cognitive_average = 15 # 8
max_string_usages = 20 # 5
max_imports = 14 # 12
max_attributes = 6 # 6
max_module_members = 9 # 7
max_imported_names = 50 # 50
max_import_from_members = 10 # 8

max_base_classes = 3
max_decorators = 5
max_annotation_complexity = 5


[tool.flakehell.plugins]
"flake8-annotations" = ["-*", "+ANN001", "+ANN2??", "+ANN301"]
"flake8-bandit" = ["+*", "-S404", "-S603", "-S101"]
"wemake-python-styleguide" = ["-*", "+WPS2??", "-WPS220", "-WPS222", "-WPS223", "-WPS202"]
