#!/bin/sh

set -euxo pipefail

function run_FOTA() {
  # Current WA for SOTA/FOTA together:
  # 1. Send FIP through SOTA request. It will fail to perform SOTA and the file is located
  #    at /var/cache/manageability/repository-tool/.
  # 2. After that, send mender file and perform SOTA.
  # 3. After system reboot, this script will check if there is SOTA perform previously. If SOTA performed previously and
  #    fip binary exist. It will call movisoc tool to flash the fip and reboot.
  if [  -f /etc/dispatcher_state ]; then
    if [  -f /var/cache/manageability/repository-tool/fip* ]; then
          echo "Found FIP."
          movisoc-fwu -a /var/cache/manageability/repository-tool/fip*
          echo "Update FIP complete. Remove FIP."
          rm /var/cache/manageability/repository-tool/fip*
          echo "Commit mender."
          mender -commit
          reboot
    fi
  fi
}


KMB_PCIE_EP_STATUS="/proc/device-tree/soc/pcie_ep@37000000/status"
THB_PCIE_EP_STATUS="/proc/device-tree/soc/pcie_ep@82000000/status"

if [ -f $KMB_PCIE_EP_STATUS ]; then
  PCIE_EP_STATUS=$KMB_PCIE_EP_STATUS
elif [ -f $THB_PCIE_EP_STATUS ]; then
  PCIE_EP_STATUS=$THB_PCIE_EP_STATUS
else
  PCIE_EP_STATUS=""
fi

# Status is okay if it is in HDDL mode.
if [ ! $PCIE_EP_STATUS == "" ]; then
    IS_HDDL=$(cat $PCIE_EP_STATUS | tr -d '\0')
    echo $IS_HDDL
    if [ $IS_HDDL == "okay" ]; then
        echo HDDL mode enabled.

	# PV3 upgrade. Any version prior to PV3 may have TPM temporarily disabled. This
	# will force a reprovision with TPM=auto in that case so it has a chance to be re-enabled
	# if it is functioning on the system.
	#   In HDDL mode, we don't have any secrets other than TLS keys, so we don't lose any
	# credentials doing this and we can regenerate TLS keys on reboot.

        if [ ! -f /etc/intel-manageability/PV3_UPGRADED ]; then
	    rm -f /etc/intel-manageability/AUTO_ENABLED || true # Allow auto-enable to work below
	    touch /etc/intel-manageability/PV3_UPGRADED # Prevent PV3 upgrade from happening more than once
        fi

        run_FOTA # this might reboot

        sed -i 's/<networkCheck>true<\/networkCheck>/<networkCheck>false<\/networkCheck>/' /etc/intel_manageability.conf

	if [ -f /etc/intel-manageability/AUTO_ENABLED ]; then
            echo "Already autoenabled."
            exit 0
	fi

        mqtt-remove-keys || true # This is necessary in case we're coming from a PV3 upgrade
        SKIP_DOCKER_CONFIGURATION=1 NO_CLOUD=1 NO_OTA_CERT=1 PROVISION_TPM=auto /usr/bin/provision-tc
        systemctl enable inbm-node.service
	touch /etc/intel-manageability/AUTO_ENABLED  # This is run AFTER node is enabled (but not started) and provision-tc succeeds, in case there is an error starting node.

        # Finally, we start inbm-node.service.
        # TODO: BC needs a provision-bc script. This is temporary:
        if [ -f /usr/bin/inbm-node ] ; then
            systemctl start inbm-node.service
        fi
    fi
fi
