#!/bin/sh

set -euxo pipefail

function run_FOTA() {
  # Current WA for SOTA/FOTA together:
  # 1. Send FIP through SOTA request. It will fail to perform SOTA and the file is located
  #    at /var/cache/manageability/repository-tool/.
  # 2. After that, send mender file and perform SOTA.
  # 3. After system reboot, this script will check if there is SOTA perform previously. If SOTA performed previously and
  #    fip binary exist. It will call movisoc tool to flash the fip and reboot.
  if [  -f /var/intel-manageability/dispatcher_state ]; then
    if [  -f /var/cache/manageability/repository-tool/fip* ]; then
          echo "Found FIP."
          movisoc-fwu -a /var/cache/manageability/repository-tool/fip*
          echo "Update FIP complete. Remove FIP."
          rm /var/cache/manageability/repository-tool/fip*
          echo "Commit mender."
          mender -commit
          reboot
    fi
  fi
}
