#!/bin/bash

set -euxo pipefail

: do not run integration tests in build
rm -rf realdocker/*test*
mkdir -p ./output/
go test -coverprofile ./trtl-coverage.out ./...
go install golang.org/x/tools/cmd/cover@v0.1.0-deprecated
cover -func=./trtl-coverage.out >./output/trtl-coverage.txt
