#!/bin/bash

# Shell script that provisions Intel(R) In-Band Manageability Framework
# Copyright (C) 2017-2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

set -eo pipefail

### The main provisioning function
function provision {

  enable_inbd
  echo "Intel(R) In-Band Manageability Provisioning Complete"
  exit 0
}

function enable_inbd {
  echo "Enabling and starting INBM Daemon"
  systemctl enable inbd
  systemctl start inbd
  sleep 1
}

provision