// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: inbs_sb.proto

package pb

import (
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetScheduleResponseData_StatusType int32

const (
	SetScheduleResponseData_STATUS_TYPE_UNSPECIFIED SetScheduleResponseData_StatusType = 0
	SetScheduleResponseData_STATUS_TYPE_UP_TO_DATE  SetScheduleResponseData_StatusType = 1
	SetScheduleResponseData_STATUS_TYPE_STARTED     SetScheduleResponseData_StatusType = 2
	SetScheduleResponseData_STATUS_TYPE_UPDATED     SetScheduleResponseData_StatusType = 3
	SetScheduleResponseData_STATUS_TYPE_FAILED      SetScheduleResponseData_StatusType = 4
)

// Enum value maps for SetScheduleResponseData_StatusType.
var (
	SetScheduleResponseData_StatusType_name = map[int32]string{
		0: "STATUS_TYPE_UNSPECIFIED",
		1: "STATUS_TYPE_UP_TO_DATE",
		2: "STATUS_TYPE_STARTED",
		3: "STATUS_TYPE_UPDATED",
		4: "STATUS_TYPE_FAILED",
	}
	SetScheduleResponseData_StatusType_value = map[string]int32{
		"STATUS_TYPE_UNSPECIFIED": 0,
		"STATUS_TYPE_UP_TO_DATE":  1,
		"STATUS_TYPE_STARTED":     2,
		"STATUS_TYPE_UPDATED":     3,
		"STATUS_TYPE_FAILED":      4,
	}
)

func (x SetScheduleResponseData_StatusType) Enum() *SetScheduleResponseData_StatusType {
	p := new(SetScheduleResponseData_StatusType)
	*p = x
	return p
}

func (x SetScheduleResponseData_StatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetScheduleResponseData_StatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_inbs_sb_proto_enumTypes[0].Descriptor()
}

func (SetScheduleResponseData_StatusType) Type() protoreflect.EnumType {
	return &file_inbs_sb_proto_enumTypes[0]
}

func (x SetScheduleResponseData_StatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetScheduleResponseData_StatusType.Descriptor instead.
func (SetScheduleResponseData_StatusType) EnumDescriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{11, 0}
}

type HandleINBMCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId   string                  `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RequestData *INBMCommandRequestData `protobuf:"bytes,2,opt,name=request_data,json=requestData,proto3" json:"request_data,omitempty"`
}

func (x *HandleINBMCommandRequest) Reset() {
	*x = HandleINBMCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleINBMCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleINBMCommandRequest) ProtoMessage() {}

func (x *HandleINBMCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleINBMCommandRequest.ProtoReflect.Descriptor instead.
func (*HandleINBMCommandRequest) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{0}
}

func (x *HandleINBMCommandRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HandleINBMCommandRequest) GetRequestData() *INBMCommandRequestData {
	if x != nil {
		return x.RequestData
	}
	return nil
}

type HandleINBMCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId    string                   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ResponseData *INBMCommandResponseData `protobuf:"bytes,2,opt,name=response_data,json=responseData,proto3" json:"response_data,omitempty"`
}

func (x *HandleINBMCommandResponse) Reset() {
	*x = HandleINBMCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleINBMCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleINBMCommandResponse) ProtoMessage() {}

func (x *HandleINBMCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleINBMCommandResponse.ProtoReflect.Descriptor instead.
func (*HandleINBMCommandResponse) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{1}
}

func (x *HandleINBMCommandResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HandleINBMCommandResponse) GetResponseData() *INBMCommandResponseData {
	if x != nil {
		return x.ResponseData
	}
	return nil
}

type INBMCommandRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*INBMCommandRequestData_PingRequestData
	//	*INBMCommandRequestData_SetScheduleRequestData
	Payload isINBMCommandRequestData_Payload `protobuf_oneof:"payload"`
}

func (x *INBMCommandRequestData) Reset() {
	*x = INBMCommandRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *INBMCommandRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INBMCommandRequestData) ProtoMessage() {}

func (x *INBMCommandRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INBMCommandRequestData.ProtoReflect.Descriptor instead.
func (*INBMCommandRequestData) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{2}
}

func (m *INBMCommandRequestData) GetPayload() isINBMCommandRequestData_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *INBMCommandRequestData) GetPingRequestData() *PingRequestData {
	if x, ok := x.GetPayload().(*INBMCommandRequestData_PingRequestData); ok {
		return x.PingRequestData
	}
	return nil
}

func (x *INBMCommandRequestData) GetSetScheduleRequestData() *SetScheduleRequestData {
	if x, ok := x.GetPayload().(*INBMCommandRequestData_SetScheduleRequestData); ok {
		return x.SetScheduleRequestData
	}
	return nil
}

type isINBMCommandRequestData_Payload interface {
	isINBMCommandRequestData_Payload()
}

type INBMCommandRequestData_PingRequestData struct {
	PingRequestData *PingRequestData `protobuf:"bytes,1,opt,name=ping_request_data,json=pingRequestData,proto3,oneof"`
}

type INBMCommandRequestData_SetScheduleRequestData struct {
	SetScheduleRequestData *SetScheduleRequestData `protobuf:"bytes,2,opt,name=set_schedule_request_data,json=setScheduleRequestData,proto3,oneof"`
}

func (*INBMCommandRequestData_PingRequestData) isINBMCommandRequestData_Payload() {}

func (*INBMCommandRequestData_SetScheduleRequestData) isINBMCommandRequestData_Payload() {}

type INBMCommandResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*INBMCommandResponseData_PingResponseData
	//	*INBMCommandResponseData_SetScheduleResponseData
	Payload isINBMCommandResponseData_Payload `protobuf_oneof:"payload"`
}

func (x *INBMCommandResponseData) Reset() {
	*x = INBMCommandResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *INBMCommandResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INBMCommandResponseData) ProtoMessage() {}

func (x *INBMCommandResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INBMCommandResponseData.ProtoReflect.Descriptor instead.
func (*INBMCommandResponseData) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{3}
}

func (m *INBMCommandResponseData) GetPayload() isINBMCommandResponseData_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *INBMCommandResponseData) GetPingResponseData() *PingResponseData {
	if x, ok := x.GetPayload().(*INBMCommandResponseData_PingResponseData); ok {
		return x.PingResponseData
	}
	return nil
}

func (x *INBMCommandResponseData) GetSetScheduleResponseData() *SetScheduleResponseData {
	if x, ok := x.GetPayload().(*INBMCommandResponseData_SetScheduleResponseData); ok {
		return x.SetScheduleResponseData
	}
	return nil
}

type isINBMCommandResponseData_Payload interface {
	isINBMCommandResponseData_Payload()
}

type INBMCommandResponseData_PingResponseData struct {
	PingResponseData *PingResponseData `protobuf:"bytes,1,opt,name=ping_response_data,json=pingResponseData,proto3,oneof"`
}

type INBMCommandResponseData_SetScheduleResponseData struct {
	SetScheduleResponseData *SetScheduleResponseData `protobuf:"bytes,2,opt,name=set_schedule_response_data,json=setScheduleResponseData,proto3,oneof"`
}

func (*INBMCommandResponseData_PingResponseData) isINBMCommandResponseData_Payload() {}

func (*INBMCommandResponseData_SetScheduleResponseData) isINBMCommandResponseData_Payload() {}

type PingRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequestData) Reset() {
	*x = PingRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequestData) ProtoMessage() {}

func (x *PingRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequestData.ProtoReflect.Descriptor instead.
func (*PingRequestData) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{4}
}

type PingResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingResponseData) Reset() {
	*x = PingResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponseData) ProtoMessage() {}

func (x *PingResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponseData.ProtoReflect.Descriptor instead.
func (*PingResponseData) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{5}
}

// TODO: re-add the validate.rules from maintenance manager to the repeated_schedules fields. prerequisite: get the validate.proto import working
type SetScheduleRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*INBMScheduledTask `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *SetScheduleRequestData) Reset() {
	*x = SetScheduleRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetScheduleRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetScheduleRequestData) ProtoMessage() {}

func (x *SetScheduleRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetScheduleRequestData.ProtoReflect.Descriptor instead.
func (*SetScheduleRequestData) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{6}
}

func (x *SetScheduleRequestData) GetTasks() []*INBMScheduledTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type INBMScheduledTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Manifests *Manifests `protobuf:"bytes,3,opt,name=manifests,proto3" json:"manifests,omitempty"`
	// Types that are assignable to Schedule:
	//
	//	*INBMScheduledTask_SingleSchedule
	//	*INBMScheduledTask_RepeatedSchedule
	Schedule isINBMScheduledTask_Schedule `protobuf_oneof:"schedule"`
}

func (x *INBMScheduledTask) Reset() {
	*x = INBMScheduledTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *INBMScheduledTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INBMScheduledTask) ProtoMessage() {}

func (x *INBMScheduledTask) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INBMScheduledTask.ProtoReflect.Descriptor instead.
func (*INBMScheduledTask) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{7}
}

func (x *INBMScheduledTask) GetManifests() *Manifests {
	if x != nil {
		return x.Manifests
	}
	return nil
}

func (m *INBMScheduledTask) GetSchedule() isINBMScheduledTask_Schedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

func (x *INBMScheduledTask) GetSingleSchedule() *SingleSchedule {
	if x, ok := x.GetSchedule().(*INBMScheduledTask_SingleSchedule); ok {
		return x.SingleSchedule
	}
	return nil
}

func (x *INBMScheduledTask) GetRepeatedSchedule() *RepeatedSchedule {
	if x, ok := x.GetSchedule().(*INBMScheduledTask_RepeatedSchedule); ok {
		return x.RepeatedSchedule
	}
	return nil
}

type isINBMScheduledTask_Schedule interface {
	isINBMScheduledTask_Schedule()
}

type INBMScheduledTask_SingleSchedule struct {
	SingleSchedule *SingleSchedule `protobuf:"bytes,1,opt,name=single_schedule,json=singleSchedule,proto3,oneof"`
}

type INBMScheduledTask_RepeatedSchedule struct {
	RepeatedSchedule *RepeatedSchedule `protobuf:"bytes,2,opt,name=repeated_schedule,json=repeatedSchedule,proto3,oneof"`
}

func (*INBMScheduledTask_SingleSchedule) isINBMScheduledTask_Schedule() {}

func (*INBMScheduledTask_RepeatedSchedule) isINBMScheduledTask_Schedule() {}

type Manifests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ManifestXml []string `protobuf:"bytes,1,rep,name=manifest_xml,json=manifestXml,proto3" json:"manifest_xml,omitempty"`
}

func (x *Manifests) Reset() {
	*x = Manifests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Manifests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifests) ProtoMessage() {}

func (x *Manifests) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifests.ProtoReflect.Descriptor instead.
func (*Manifests) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{8}
}

func (x *Manifests) GetManifestXml() []string {
	if x != nil {
		return x.ManifestXml
	}
	return nil
}

type SingleSchedule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *SingleSchedule) Reset() {
	*x = SingleSchedule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleSchedule) ProtoMessage() {}

func (x *SingleSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleSchedule.ProtoReflect.Descriptor instead.
func (*SingleSchedule) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{9}
}

func (x *SingleSchedule) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SingleSchedule) GetEndTime() *timestamp.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type RepeatedSchedule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duration     *duration.Duration `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`                               // should be between 1 second and 86400 seconds (24 hours worth of seconds)
	CronMinutes  string             `protobuf:"bytes,2,opt,name=cron_minutes,json=cronMinutes,proto3" json:"cron_minutes,omitempty"`      // cron style minutes (0-59)
	CronHours    string             `protobuf:"bytes,3,opt,name=cron_hours,json=cronHours,proto3" json:"cron_hours,omitempty"`            // cron style hours (0-23)
	CronDayMonth string             `protobuf:"bytes,4,opt,name=cron_day_month,json=cronDayMonth,proto3" json:"cron_day_month,omitempty"` // cron style day of month (0-31)
	CronMonth    string             `protobuf:"bytes,5,opt,name=cron_month,json=cronMonth,proto3" json:"cron_month,omitempty"`            // cron style month (1-12)
	CronDayWeek  string             `protobuf:"bytes,6,opt,name=cron_day_week,json=cronDayWeek,proto3" json:"cron_day_week,omitempty"`    // cron style day of week (0-6)
}

func (x *RepeatedSchedule) Reset() {
	*x = RepeatedSchedule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedSchedule) ProtoMessage() {}

func (x *RepeatedSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedSchedule.ProtoReflect.Descriptor instead.
func (*RepeatedSchedule) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{10}
}

func (x *RepeatedSchedule) GetDuration() *duration.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *RepeatedSchedule) GetCronMinutes() string {
	if x != nil {
		return x.CronMinutes
	}
	return ""
}

func (x *RepeatedSchedule) GetCronHours() string {
	if x != nil {
		return x.CronHours
	}
	return ""
}

func (x *RepeatedSchedule) GetCronDayMonth() string {
	if x != nil {
		return x.CronDayMonth
	}
	return ""
}

func (x *RepeatedSchedule) GetCronMonth() string {
	if x != nil {
		return x.CronMonth
	}
	return ""
}

func (x *RepeatedSchedule) GetCronDayWeek() string {
	if x != nil {
		return x.CronDayWeek
	}
	return ""
}

type SetScheduleResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusType SetScheduleResponseData_StatusType `protobuf:"varint,1,opt,name=status_type,json=statusType,proto3,enum=inbs.v1.SetScheduleResponseData_StatusType" json:"status_type,omitempty"`
}

func (x *SetScheduleResponseData) Reset() {
	*x = SetScheduleResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetScheduleResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetScheduleResponseData) ProtoMessage() {}

func (x *SetScheduleResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetScheduleResponseData.ProtoReflect.Descriptor instead.
func (*SetScheduleResponseData) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{11}
}

func (x *SetScheduleResponseData) GetStatusType() SetScheduleResponseData_StatusType {
	if x != nil {
		return x.StatusType
	}
	return SetScheduleResponseData_STATUS_TYPE_UNSPECIFIED
}

var File_inbs_sb_proto protoreflect.FileDescriptor

var file_inbs_sb_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x6e, 0x62, 0x73, 0x5f, 0x73, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x18, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x49, 0x4e, 0x42, 0x4d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x42, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x69, 0x6e, 0x62,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x4e, 0x42, 0x4d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0b, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x81, 0x01, 0x0a, 0x19, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x49, 0x4e, 0x42, 0x4d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x45, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x69,
	0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x4e, 0x42, 0x4d, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0c,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0xc9, 0x01, 0x0a,
	0x16, 0x49, 0x4e, 0x42, 0x4d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x46, 0x0a, 0x11, 0x70, 0x69, 0x6e, 0x67, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0f,
	0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x5c, 0x0a, 0x19, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x16, 0x73, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x42, 0x09, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xd0, 0x01, 0x0a, 0x17, 0x49, 0x4e, 0x42,
	0x4d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x49, 0x0a, 0x12, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x10, 0x70,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x5f, 0x0a, 0x1a, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65,
	0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x17, 0x73, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x12,
	0x0a, 0x10, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x4a, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x30, 0x0a, 0x05,
	0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x6e,
	0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x4e, 0x42, 0x4d, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x22, 0xdf,
	0x01, 0x0a, 0x11, 0x49, 0x4e, 0x42, 0x4d, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64,
	0x54, 0x61, 0x73, 0x6b, 0x12, 0x30, 0x0a, 0x09, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x73, 0x52, 0x09, 0x6d, 0x61, 0x6e,
	0x69, 0x66, 0x65, 0x73, 0x74, 0x73, 0x12, 0x42, 0x0a, 0x0f, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65,
	0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x73, 0x69, 0x6e, 0x67,
	0x6c, 0x65, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x48, 0x0a, 0x11, 0x72, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x48, 0x00, 0x52, 0x10, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x22, 0x2e, 0x0a, 0x09, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x73, 0x12, 0x21, 0x0a,
	0x0c, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x5f, 0x78, 0x6d, 0x6c, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x58, 0x6d, 0x6c,
	0x22, 0x82, 0x01, 0x0a, 0x0e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x35,
	0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xf4, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x6f, 0x6e, 0x5f, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x72, 0x6f, 0x6e, 0x4d, 0x69, 0x6e,
	0x75, 0x74, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x6f, 0x6e, 0x5f, 0x68, 0x6f, 0x75,
	0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x6f, 0x6e, 0x48, 0x6f,
	0x75, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x72, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x79, 0x5f,
	0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x72, 0x6f,
	0x6e, 0x44, 0x61, 0x79, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x6f,
	0x6e, 0x5f, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x72, 0x6f, 0x6e, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x22, 0x0a, 0x0d, 0x63, 0x72, 0x6f, 0x6e,
	0x5f, 0x64, 0x61, 0x79, 0x5f, 0x77, 0x65, 0x65, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x72, 0x6f, 0x6e, 0x44, 0x61, 0x79, 0x57, 0x65, 0x65, 0x6b, 0x22, 0xf9, 0x01, 0x0a,
	0x17, 0x53, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x4c, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e,
	0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x55, 0x50, 0x5f, 0x54, 0x4f, 0x5f, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x17,
	0x0a, 0x13, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x54,
	0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x44, 0x10, 0x03,
	0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x32, 0x6f, 0x0a, 0x0d, 0x49, 0x4e, 0x42, 0x53,
	0x53, 0x42, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x11, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x49, 0x4e, 0x42, 0x4d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x22,
	0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x49,
	0x4e, 0x42, 0x4d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x1a, 0x21, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x49, 0x4e, 0x42, 0x4d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x28, 0x01, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_inbs_sb_proto_rawDescOnce sync.Once
	file_inbs_sb_proto_rawDescData = file_inbs_sb_proto_rawDesc
)

func file_inbs_sb_proto_rawDescGZIP() []byte {
	file_inbs_sb_proto_rawDescOnce.Do(func() {
		file_inbs_sb_proto_rawDescData = protoimpl.X.CompressGZIP(file_inbs_sb_proto_rawDescData)
	})
	return file_inbs_sb_proto_rawDescData
}

var file_inbs_sb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inbs_sb_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_inbs_sb_proto_goTypes = []interface{}{
	(SetScheduleResponseData_StatusType)(0), // 0: inbs.v1.SetScheduleResponseData.StatusType
	(*HandleINBMCommandRequest)(nil),        // 1: inbs.v1.HandleINBMCommandRequest
	(*HandleINBMCommandResponse)(nil),       // 2: inbs.v1.HandleINBMCommandResponse
	(*INBMCommandRequestData)(nil),          // 3: inbs.v1.INBMCommandRequestData
	(*INBMCommandResponseData)(nil),         // 4: inbs.v1.INBMCommandResponseData
	(*PingRequestData)(nil),                 // 5: inbs.v1.PingRequestData
	(*PingResponseData)(nil),                // 6: inbs.v1.PingResponseData
	(*SetScheduleRequestData)(nil),          // 7: inbs.v1.SetScheduleRequestData
	(*INBMScheduledTask)(nil),               // 8: inbs.v1.INBMScheduledTask
	(*Manifests)(nil),                       // 9: inbs.v1.Manifests
	(*SingleSchedule)(nil),                  // 10: inbs.v1.SingleSchedule
	(*RepeatedSchedule)(nil),                // 11: inbs.v1.RepeatedSchedule
	(*SetScheduleResponseData)(nil),         // 12: inbs.v1.SetScheduleResponseData
	(*timestamp.Timestamp)(nil),             // 13: google.protobuf.Timestamp
	(*duration.Duration)(nil),               // 14: google.protobuf.Duration
}
var file_inbs_sb_proto_depIdxs = []int32{
	3,  // 0: inbs.v1.HandleINBMCommandRequest.request_data:type_name -> inbs.v1.INBMCommandRequestData
	4,  // 1: inbs.v1.HandleINBMCommandResponse.response_data:type_name -> inbs.v1.INBMCommandResponseData
	5,  // 2: inbs.v1.INBMCommandRequestData.ping_request_data:type_name -> inbs.v1.PingRequestData
	7,  // 3: inbs.v1.INBMCommandRequestData.set_schedule_request_data:type_name -> inbs.v1.SetScheduleRequestData
	6,  // 4: inbs.v1.INBMCommandResponseData.ping_response_data:type_name -> inbs.v1.PingResponseData
	12, // 5: inbs.v1.INBMCommandResponseData.set_schedule_response_data:type_name -> inbs.v1.SetScheduleResponseData
	8,  // 6: inbs.v1.SetScheduleRequestData.tasks:type_name -> inbs.v1.INBMScheduledTask
	9,  // 7: inbs.v1.INBMScheduledTask.manifests:type_name -> inbs.v1.Manifests
	10, // 8: inbs.v1.INBMScheduledTask.single_schedule:type_name -> inbs.v1.SingleSchedule
	11, // 9: inbs.v1.INBMScheduledTask.repeated_schedule:type_name -> inbs.v1.RepeatedSchedule
	13, // 10: inbs.v1.SingleSchedule.start_time:type_name -> google.protobuf.Timestamp
	13, // 11: inbs.v1.SingleSchedule.end_time:type_name -> google.protobuf.Timestamp
	14, // 12: inbs.v1.RepeatedSchedule.duration:type_name -> google.protobuf.Duration
	0,  // 13: inbs.v1.SetScheduleResponseData.status_type:type_name -> inbs.v1.SetScheduleResponseData.StatusType
	2,  // 14: inbs.v1.INBSSBService.HandleINBMCommand:input_type -> inbs.v1.HandleINBMCommandResponse
	1,  // 15: inbs.v1.INBSSBService.HandleINBMCommand:output_type -> inbs.v1.HandleINBMCommandRequest
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_inbs_sb_proto_init() }
func file_inbs_sb_proto_init() {
	if File_inbs_sb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inbs_sb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleINBMCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleINBMCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*INBMCommandRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*INBMCommandResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetScheduleRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*INBMScheduledTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Manifests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleSchedule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedSchedule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetScheduleResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_inbs_sb_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*INBMCommandRequestData_PingRequestData)(nil),
		(*INBMCommandRequestData_SetScheduleRequestData)(nil),
	}
	file_inbs_sb_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*INBMCommandResponseData_PingResponseData)(nil),
		(*INBMCommandResponseData_SetScheduleResponseData)(nil),
	}
	file_inbs_sb_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*INBMScheduledTask_SingleSchedule)(nil),
		(*INBMScheduledTask_RepeatedSchedule)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inbs_sb_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inbs_sb_proto_goTypes,
		DependencyIndexes: file_inbs_sb_proto_depIdxs,
		EnumInfos:         file_inbs_sb_proto_enumTypes,
		MessageInfos:      file_inbs_sb_proto_msgTypes,
	}.Build()
	File_inbs_sb_proto = out.File
	file_inbs_sb_proto_rawDesc = nil
	file_inbs_sb_proto_goTypes = nil
	file_inbs_sb_proto_depIdxs = nil
}
