// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: inbs_sb.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetSOTAScheduleResponsePayload_StatusType int32

const (
	SetSOTAScheduleResponsePayload_STATUS_TYPE_UNSPECIFIED SetSOTAScheduleResponsePayload_StatusType = 0
	SetSOTAScheduleResponsePayload_STATUS_TYPE_UP_TO_DATE  SetSOTAScheduleResponsePayload_StatusType = 1
	SetSOTAScheduleResponsePayload_STATUS_TYPE_STARTED     SetSOTAScheduleResponsePayload_StatusType = 2
	SetSOTAScheduleResponsePayload_STATUS_TYPE_UPDATED     SetSOTAScheduleResponsePayload_StatusType = 3
	SetSOTAScheduleResponsePayload_STATUS_TYPE_FAILED      SetSOTAScheduleResponsePayload_StatusType = 4
)

// Enum value maps for SetSOTAScheduleResponsePayload_StatusType.
var (
	SetSOTAScheduleResponsePayload_StatusType_name = map[int32]string{
		0: "STATUS_TYPE_UNSPECIFIED",
		1: "STATUS_TYPE_UP_TO_DATE",
		2: "STATUS_TYPE_STARTED",
		3: "STATUS_TYPE_UPDATED",
		4: "STATUS_TYPE_FAILED",
	}
	SetSOTAScheduleResponsePayload_StatusType_value = map[string]int32{
		"STATUS_TYPE_UNSPECIFIED": 0,
		"STATUS_TYPE_UP_TO_DATE":  1,
		"STATUS_TYPE_STARTED":     2,
		"STATUS_TYPE_UPDATED":     3,
		"STATUS_TYPE_FAILED":      4,
	}
)

func (x SetSOTAScheduleResponsePayload_StatusType) Enum() *SetSOTAScheduleResponsePayload_StatusType {
	p := new(SetSOTAScheduleResponsePayload_StatusType)
	*p = x
	return p
}

func (x SetSOTAScheduleResponsePayload_StatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetSOTAScheduleResponsePayload_StatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_inbs_sb_proto_enumTypes[0].Descriptor()
}

func (SetSOTAScheduleResponsePayload_StatusType) Type() protoreflect.EnumType {
	return &file_inbs_sb_proto_enumTypes[0]
}

func (x SetSOTAScheduleResponsePayload_StatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetSOTAScheduleResponsePayload_StatusType.Descriptor instead.
func (SetSOTAScheduleResponsePayload_StatusType) EnumDescriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{7, 0}
}

type INBMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId   string              `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RequestData *INBMRequestPayload `protobuf:"bytes,2,opt,name=request_data,json=requestData,proto3" json:"request_data,omitempty"`
}

func (x *INBMRequest) Reset() {
	*x = INBMRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *INBMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INBMRequest) ProtoMessage() {}

func (x *INBMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INBMRequest.ProtoReflect.Descriptor instead.
func (*INBMRequest) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{0}
}

func (x *INBMRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *INBMRequest) GetRequestData() *INBMRequestPayload {
	if x != nil {
		return x.RequestData
	}
	return nil
}

type INBMResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId    string               `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ResponseData *INBMResponsePayload `protobuf:"bytes,2,opt,name=response_data,json=responseData,proto3" json:"response_data,omitempty"`
}

func (x *INBMResponse) Reset() {
	*x = INBMResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *INBMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INBMResponse) ProtoMessage() {}

func (x *INBMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INBMResponse.ProtoReflect.Descriptor instead.
func (*INBMResponse) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{1}
}

func (x *INBMResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *INBMResponse) GetResponseData() *INBMResponsePayload {
	if x != nil {
		return x.ResponseData
	}
	return nil
}

type INBMRequestPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*INBMRequestPayload_PingRequest
	//	*INBMRequestPayload_SetSotaScheduleRequest
	Payload isINBMRequestPayload_Payload `protobuf_oneof:"payload"`
}

func (x *INBMRequestPayload) Reset() {
	*x = INBMRequestPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *INBMRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INBMRequestPayload) ProtoMessage() {}

func (x *INBMRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INBMRequestPayload.ProtoReflect.Descriptor instead.
func (*INBMRequestPayload) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{2}
}

func (m *INBMRequestPayload) GetPayload() isINBMRequestPayload_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *INBMRequestPayload) GetPingRequest() *PingRequestPayload {
	if x, ok := x.GetPayload().(*INBMRequestPayload_PingRequest); ok {
		return x.PingRequest
	}
	return nil
}

func (x *INBMRequestPayload) GetSetSotaScheduleRequest() *SetSOTAScheduleRequestPayload {
	if x, ok := x.GetPayload().(*INBMRequestPayload_SetSotaScheduleRequest); ok {
		return x.SetSotaScheduleRequest
	}
	return nil
}

type isINBMRequestPayload_Payload interface {
	isINBMRequestPayload_Payload()
}

type INBMRequestPayload_PingRequest struct {
	PingRequest *PingRequestPayload `protobuf:"bytes,1,opt,name=ping_request,json=pingRequest,proto3,oneof"`
}

type INBMRequestPayload_SetSotaScheduleRequest struct {
	SetSotaScheduleRequest *SetSOTAScheduleRequestPayload `protobuf:"bytes,2,opt,name=set_sota_schedule_request,json=setSotaScheduleRequest,proto3,oneof"`
}

func (*INBMRequestPayload_PingRequest) isINBMRequestPayload_Payload() {}

func (*INBMRequestPayload_SetSotaScheduleRequest) isINBMRequestPayload_Payload() {}

type INBMResponsePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*INBMResponsePayload_PingResponse
	//	*INBMResponsePayload_SetSotaScheduleResponse
	Payload isINBMResponsePayload_Payload `protobuf_oneof:"payload"`
}

func (x *INBMResponsePayload) Reset() {
	*x = INBMResponsePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *INBMResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INBMResponsePayload) ProtoMessage() {}

func (x *INBMResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INBMResponsePayload.ProtoReflect.Descriptor instead.
func (*INBMResponsePayload) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{3}
}

func (m *INBMResponsePayload) GetPayload() isINBMResponsePayload_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *INBMResponsePayload) GetPingResponse() *PingResponsePayload {
	if x, ok := x.GetPayload().(*INBMResponsePayload_PingResponse); ok {
		return x.PingResponse
	}
	return nil
}

func (x *INBMResponsePayload) GetSetSotaScheduleResponse() *SetSOTAScheduleResponsePayload {
	if x, ok := x.GetPayload().(*INBMResponsePayload_SetSotaScheduleResponse); ok {
		return x.SetSotaScheduleResponse
	}
	return nil
}

type isINBMResponsePayload_Payload interface {
	isINBMResponsePayload_Payload()
}

type INBMResponsePayload_PingResponse struct {
	PingResponse *PingResponsePayload `protobuf:"bytes,1,opt,name=ping_response,json=pingResponse,proto3,oneof"`
}

type INBMResponsePayload_SetSotaScheduleResponse struct {
	SetSotaScheduleResponse *SetSOTAScheduleResponsePayload `protobuf:"bytes,2,opt,name=set_sota_schedule_response,json=setSotaScheduleResponse,proto3,oneof"`
}

func (*INBMResponsePayload_PingResponse) isINBMResponsePayload_Payload() {}

func (*INBMResponsePayload_SetSotaScheduleResponse) isINBMResponsePayload_Payload() {}

type PingRequestPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequestPayload) Reset() {
	*x = PingRequestPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequestPayload) ProtoMessage() {}

func (x *PingRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequestPayload.ProtoReflect.Descriptor instead.
func (*PingRequestPayload) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{4}
}

type PingResponsePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingResponsePayload) Reset() {
	*x = PingResponsePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponsePayload) ProtoMessage() {}

func (x *PingResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponsePayload.ProtoReflect.Descriptor instead.
func (*PingResponsePayload) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{5}
}

// TODO: re-add the validate.rules from maintenance manager to the repeated_schedules fields. prerequisite: get the validate.proto import working
type SetSOTAScheduleRequestPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdateSource      *SetSOTAScheduleRequestPayload_UpdateSource   `protobuf:"bytes,1,opt,name=update_source,json=updateSource,proto3" json:"update_source,omitempty"`
	UpdateSchedule    *SetSOTAScheduleRequestPayload_UpdateSchedule `protobuf:"bytes,2,opt,name=update_schedule,json=updateSchedule,proto3" json:"update_schedule,omitempty"`
	InstalledPackages string                                        `protobuf:"bytes,3,opt,name=installed_packages,json=installedPackages,proto3" json:"installed_packages,omitempty"` // Freeform text, OS-dependent. A list of package names, one per line (newline separated). Should not contain version info.
}

func (x *SetSOTAScheduleRequestPayload) Reset() {
	*x = SetSOTAScheduleRequestPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSOTAScheduleRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSOTAScheduleRequestPayload) ProtoMessage() {}

func (x *SetSOTAScheduleRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSOTAScheduleRequestPayload.ProtoReflect.Descriptor instead.
func (*SetSOTAScheduleRequestPayload) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{6}
}

func (x *SetSOTAScheduleRequestPayload) GetUpdateSource() *SetSOTAScheduleRequestPayload_UpdateSource {
	if x != nil {
		return x.UpdateSource
	}
	return nil
}

func (x *SetSOTAScheduleRequestPayload) GetUpdateSchedule() *SetSOTAScheduleRequestPayload_UpdateSchedule {
	if x != nil {
		return x.UpdateSchedule
	}
	return nil
}

func (x *SetSOTAScheduleRequestPayload) GetInstalledPackages() string {
	if x != nil {
		return x.InstalledPackages
	}
	return ""
}

type SetSOTAScheduleResponsePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusType SetSOTAScheduleResponsePayload_StatusType `protobuf:"varint,1,opt,name=status_type,json=statusType,proto3,enum=inbs.v1.SetSOTAScheduleResponsePayload_StatusType" json:"status_type,omitempty"`
}

func (x *SetSOTAScheduleResponsePayload) Reset() {
	*x = SetSOTAScheduleResponsePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSOTAScheduleResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSOTAScheduleResponsePayload) ProtoMessage() {}

func (x *SetSOTAScheduleResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSOTAScheduleResponsePayload.ProtoReflect.Descriptor instead.
func (*SetSOTAScheduleResponsePayload) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{7}
}

func (x *SetSOTAScheduleResponsePayload) GetStatusType() SetSOTAScheduleResponsePayload_StatusType {
	if x != nil {
		return x.StatusType
	}
	return SetSOTAScheduleResponsePayload_STATUS_TYPE_UNSPECIFIED
}

type SetSOTAScheduleRequestPayload_UpdateSource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KernelCommand string   `protobuf:"bytes,1,opt,name=kernel_command,json=kernelCommand,proto3" json:"kernel_command,omitempty"` // Kernel command line
	OsRepoUrl     string   `protobuf:"bytes,2,opt,name=os_repo_url,json=osRepoUrl,proto3" json:"os_repo_url,omitempty"`           // 'DEB822 Source Format' url to the public repository
	CustomRepos   []string `protobuf:"bytes,3,rep,name=custom_repos,json=customRepos,proto3" json:"custom_repos,omitempty"`       // 'DEB822 Source Format' entries for Debian style OSs
}

func (x *SetSOTAScheduleRequestPayload_UpdateSource) Reset() {
	*x = SetSOTAScheduleRequestPayload_UpdateSource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSOTAScheduleRequestPayload_UpdateSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSOTAScheduleRequestPayload_UpdateSource) ProtoMessage() {}

func (x *SetSOTAScheduleRequestPayload_UpdateSource) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSOTAScheduleRequestPayload_UpdateSource.ProtoReflect.Descriptor instead.
func (*SetSOTAScheduleRequestPayload_UpdateSource) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{6, 0}
}

func (x *SetSOTAScheduleRequestPayload_UpdateSource) GetKernelCommand() string {
	if x != nil {
		return x.KernelCommand
	}
	return ""
}

func (x *SetSOTAScheduleRequestPayload_UpdateSource) GetOsRepoUrl() string {
	if x != nil {
		return x.OsRepoUrl
	}
	return ""
}

func (x *SetSOTAScheduleRequestPayload_UpdateSource) GetCustomRepos() []string {
	if x != nil {
		return x.CustomRepos
	}
	return nil
}

type SetSOTAScheduleRequestPayload_UpdateSchedule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SingleSchedules   []*SetSOTAScheduleRequestPayload_UpdateSchedule_SingleSchedule   `protobuf:"bytes,1,rep,name=single_schedules,json=singleSchedules,proto3" json:"single_schedules,omitempty"`
	RepeatedSchedules []*SetSOTAScheduleRequestPayload_UpdateSchedule_RepeatedSchedule `protobuf:"bytes,2,rep,name=repeated_schedules,json=repeatedSchedules,proto3" json:"repeated_schedules,omitempty"`
}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule) Reset() {
	*x = SetSOTAScheduleRequestPayload_UpdateSchedule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSOTAScheduleRequestPayload_UpdateSchedule) ProtoMessage() {}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSOTAScheduleRequestPayload_UpdateSchedule.ProtoReflect.Descriptor instead.
func (*SetSOTAScheduleRequestPayload_UpdateSchedule) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{6, 1}
}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule) GetSingleSchedules() []*SetSOTAScheduleRequestPayload_UpdateSchedule_SingleSchedule {
	if x != nil {
		return x.SingleSchedules
	}
	return nil
}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule) GetRepeatedSchedules() []*SetSOTAScheduleRequestPayload_UpdateSchedule_RepeatedSchedule {
	if x != nil {
		return x.RepeatedSchedules
	}
	return nil
}

type SetSOTAScheduleRequestPayload_UpdateSchedule_SingleSchedule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Start time for the schedule (required)
	EndTime   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // Start time for the schedule (optional)
}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule_SingleSchedule) Reset() {
	*x = SetSOTAScheduleRequestPayload_UpdateSchedule_SingleSchedule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule_SingleSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSOTAScheduleRequestPayload_UpdateSchedule_SingleSchedule) ProtoMessage() {}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule_SingleSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSOTAScheduleRequestPayload_UpdateSchedule_SingleSchedule.ProtoReflect.Descriptor instead.
func (*SetSOTAScheduleRequestPayload_UpdateSchedule_SingleSchedule) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{6, 1, 0}
}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule_SingleSchedule) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule_SingleSchedule) GetEndTime() *timestamp.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type SetSOTAScheduleRequestPayload_UpdateSchedule_RepeatedSchedule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DurationSeconds uint32 `protobuf:"varint,1,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // between 1 second and 86400 seconds (24 hours worth of seconds)
	CronMinutes     string `protobuf:"bytes,2,opt,name=cron_minutes,json=cronMinutes,proto3" json:"cron_minutes,omitempty"`              // cron style minutes (0-59)
	CronHours       string `protobuf:"bytes,3,opt,name=cron_hours,json=cronHours,proto3" json:"cron_hours,omitempty"`                    // cron style hours (0-23)
	CronDayMonth    string `protobuf:"bytes,4,opt,name=cron_day_month,json=cronDayMonth,proto3" json:"cron_day_month,omitempty"`         // cron style day of month (0-31)
	CronMonth       string `protobuf:"bytes,5,opt,name=cron_month,json=cronMonth,proto3" json:"cron_month,omitempty"`                    // cron style month (1-12)
	CronDayWeek     string `protobuf:"bytes,6,opt,name=cron_day_week,json=cronDayWeek,proto3" json:"cron_day_week,omitempty"`            // cron style day of week (0-6)
}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule_RepeatedSchedule) Reset() {
	*x = SetSOTAScheduleRequestPayload_UpdateSchedule_RepeatedSchedule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule_RepeatedSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSOTAScheduleRequestPayload_UpdateSchedule_RepeatedSchedule) ProtoMessage() {}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule_RepeatedSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSOTAScheduleRequestPayload_UpdateSchedule_RepeatedSchedule.ProtoReflect.Descriptor instead.
func (*SetSOTAScheduleRequestPayload_UpdateSchedule_RepeatedSchedule) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{6, 1, 1}
}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule_RepeatedSchedule) GetDurationSeconds() uint32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule_RepeatedSchedule) GetCronMinutes() string {
	if x != nil {
		return x.CronMinutes
	}
	return ""
}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule_RepeatedSchedule) GetCronHours() string {
	if x != nil {
		return x.CronHours
	}
	return ""
}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule_RepeatedSchedule) GetCronDayMonth() string {
	if x != nil {
		return x.CronDayMonth
	}
	return ""
}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule_RepeatedSchedule) GetCronMonth() string {
	if x != nil {
		return x.CronMonth
	}
	return ""
}

func (x *SetSOTAScheduleRequestPayload_UpdateSchedule_RepeatedSchedule) GetCronDayWeek() string {
	if x != nil {
		return x.CronDayWeek
	}
	return ""
}

var File_inbs_sb_proto protoreflect.FileDescriptor

var file_inbs_sb_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x6e, 0x62, 0x73, 0x5f, 0x73, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x0b, 0x49, 0x4e, 0x42,
	0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x4e, 0x42, 0x4d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x70, 0x0a, 0x0c, 0x49, 0x4e, 0x42, 0x4d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x41, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x4e, 0x42, 0x4d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x0c, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0xc6, 0x01, 0x0a, 0x12, 0x49, 0x4e,
	0x42, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x40, 0x0a, 0x0c, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x63, 0x0a, 0x19, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x6f, 0x74, 0x61, 0x5f, 0x73,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x74, 0x53, 0x4f, 0x54, 0x41, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52,
	0x16, 0x73, 0x65, 0x74, 0x53, 0x6f, 0x74, 0x61, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0xcd, 0x01, 0x0a, 0x13, 0x49, 0x4e, 0x42, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x43, 0x0a, 0x0d, 0x70, 0x69,
	0x6e, 0x67, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48,
	0x00, 0x52, 0x0c, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x66, 0x0a, 0x1a, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x6f, 0x74, 0x61, 0x5f, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65,
	0x74, 0x53, 0x4f, 0x54, 0x41, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x17,
	0x73, 0x65, 0x74, 0x53, 0x6f, 0x74, 0x61, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0xed, 0x07, 0x0a, 0x1d, 0x53, 0x65, 0x74, 0x53, 0x4f, 0x54, 0x41, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x58, 0x0a, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x4f, 0x54, 0x41, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x0c, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x0f, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x74, 0x53, 0x4f, 0x54, 0x41, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x0e, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x65, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x78, 0x0a, 0x0c, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6b, 0x65,
	0x72, 0x6e, 0x65, 0x6c, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x1e, 0x0a, 0x0b, 0x6f, 0x73, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x55, 0x72,
	0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x70, 0x6f,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x52,
	0x65, 0x70, 0x6f, 0x73, 0x1a, 0xe8, 0x04, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x6f, 0x0a, 0x10, 0x73, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x44, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x53,
	0x4f, 0x54, 0x41, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x0f, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x75, 0x0a, 0x12, 0x72, 0x65, 0x70, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x46, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x74, 0x53, 0x4f, 0x54, 0x41, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x52, 0x65, 0x70, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x11, 0x72, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x1a,
	0x82, 0x01, 0x0a, 0x0e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x35, 0x0a,
	0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x1a, 0xe8, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x6f, 0x6e, 0x5f, 0x6d, 0x69, 0x6e,
	0x75, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x72, 0x6f, 0x6e,
	0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x6f, 0x6e, 0x5f,
	0x68, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x6f,
	0x6e, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x72, 0x6f, 0x6e, 0x5f, 0x64,
	0x61, 0x79, 0x5f, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x72, 0x6f, 0x6e, 0x44, 0x61, 0x79, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x6f, 0x6e, 0x5f, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x6f, 0x6e, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x22, 0x0a, 0x0d, 0x63,
	0x72, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x79, 0x5f, 0x77, 0x65, 0x65, 0x6b, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x72, 0x6f, 0x6e, 0x44, 0x61, 0x79, 0x57, 0x65, 0x65, 0x6b, 0x22,
	0x87, 0x02, 0x0a, 0x1e, 0x53, 0x65, 0x74, 0x53, 0x4f, 0x54, 0x41, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x53, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x32, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x4f, 0x54, 0x41, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x55, 0x50, 0x5f, 0x54, 0x4f, 0x5f, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12,
	0x17, 0x0a, 0x13, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53,
	0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x44, 0x10,
	0x03, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x32, 0x4f, 0x0a, 0x0d, 0x49, 0x4e, 0x42,
	0x53, 0x53, 0x42, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x49, 0x4e,
	0x42, 0x4d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x15, 0x2e, 0x69, 0x6e, 0x62, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x4e, 0x42, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x1a, 0x14, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x4e, 0x42, 0x4d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x28, 0x01, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_inbs_sb_proto_rawDescOnce sync.Once
	file_inbs_sb_proto_rawDescData = file_inbs_sb_proto_rawDesc
)

func file_inbs_sb_proto_rawDescGZIP() []byte {
	file_inbs_sb_proto_rawDescOnce.Do(func() {
		file_inbs_sb_proto_rawDescData = protoimpl.X.CompressGZIP(file_inbs_sb_proto_rawDescData)
	})
	return file_inbs_sb_proto_rawDescData
}

var file_inbs_sb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inbs_sb_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_inbs_sb_proto_goTypes = []interface{}{
	(SetSOTAScheduleResponsePayload_StatusType)(0),                        // 0: inbs.v1.SetSOTAScheduleResponsePayload.StatusType
	(*INBMRequest)(nil),                                                   // 1: inbs.v1.INBMRequest
	(*INBMResponse)(nil),                                                  // 2: inbs.v1.INBMResponse
	(*INBMRequestPayload)(nil),                                            // 3: inbs.v1.INBMRequestPayload
	(*INBMResponsePayload)(nil),                                           // 4: inbs.v1.INBMResponsePayload
	(*PingRequestPayload)(nil),                                            // 5: inbs.v1.PingRequestPayload
	(*PingResponsePayload)(nil),                                           // 6: inbs.v1.PingResponsePayload
	(*SetSOTAScheduleRequestPayload)(nil),                                 // 7: inbs.v1.SetSOTAScheduleRequestPayload
	(*SetSOTAScheduleResponsePayload)(nil),                                // 8: inbs.v1.SetSOTAScheduleResponsePayload
	(*SetSOTAScheduleRequestPayload_UpdateSource)(nil),                    // 9: inbs.v1.SetSOTAScheduleRequestPayload.UpdateSource
	(*SetSOTAScheduleRequestPayload_UpdateSchedule)(nil),                  // 10: inbs.v1.SetSOTAScheduleRequestPayload.UpdateSchedule
	(*SetSOTAScheduleRequestPayload_UpdateSchedule_SingleSchedule)(nil),   // 11: inbs.v1.SetSOTAScheduleRequestPayload.UpdateSchedule.SingleSchedule
	(*SetSOTAScheduleRequestPayload_UpdateSchedule_RepeatedSchedule)(nil), // 12: inbs.v1.SetSOTAScheduleRequestPayload.UpdateSchedule.RepeatedSchedule
	(*timestamp.Timestamp)(nil),                                           // 13: google.protobuf.Timestamp
}
var file_inbs_sb_proto_depIdxs = []int32{
	3,  // 0: inbs.v1.INBMRequest.request_data:type_name -> inbs.v1.INBMRequestPayload
	4,  // 1: inbs.v1.INBMResponse.response_data:type_name -> inbs.v1.INBMResponsePayload
	5,  // 2: inbs.v1.INBMRequestPayload.ping_request:type_name -> inbs.v1.PingRequestPayload
	7,  // 3: inbs.v1.INBMRequestPayload.set_sota_schedule_request:type_name -> inbs.v1.SetSOTAScheduleRequestPayload
	6,  // 4: inbs.v1.INBMResponsePayload.ping_response:type_name -> inbs.v1.PingResponsePayload
	8,  // 5: inbs.v1.INBMResponsePayload.set_sota_schedule_response:type_name -> inbs.v1.SetSOTAScheduleResponsePayload
	9,  // 6: inbs.v1.SetSOTAScheduleRequestPayload.update_source:type_name -> inbs.v1.SetSOTAScheduleRequestPayload.UpdateSource
	10, // 7: inbs.v1.SetSOTAScheduleRequestPayload.update_schedule:type_name -> inbs.v1.SetSOTAScheduleRequestPayload.UpdateSchedule
	0,  // 8: inbs.v1.SetSOTAScheduleResponsePayload.status_type:type_name -> inbs.v1.SetSOTAScheduleResponsePayload.StatusType
	11, // 9: inbs.v1.SetSOTAScheduleRequestPayload.UpdateSchedule.single_schedules:type_name -> inbs.v1.SetSOTAScheduleRequestPayload.UpdateSchedule.SingleSchedule
	12, // 10: inbs.v1.SetSOTAScheduleRequestPayload.UpdateSchedule.repeated_schedules:type_name -> inbs.v1.SetSOTAScheduleRequestPayload.UpdateSchedule.RepeatedSchedule
	13, // 11: inbs.v1.SetSOTAScheduleRequestPayload.UpdateSchedule.SingleSchedule.start_time:type_name -> google.protobuf.Timestamp
	13, // 12: inbs.v1.SetSOTAScheduleRequestPayload.UpdateSchedule.SingleSchedule.end_time:type_name -> google.protobuf.Timestamp
	2,  // 13: inbs.v1.INBSSBService.INBMCommand:input_type -> inbs.v1.INBMResponse
	1,  // 14: inbs.v1.INBSSBService.INBMCommand:output_type -> inbs.v1.INBMRequest
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_inbs_sb_proto_init() }
func file_inbs_sb_proto_init() {
	if File_inbs_sb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inbs_sb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*INBMRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*INBMResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*INBMRequestPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*INBMResponsePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequestPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponsePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSOTAScheduleRequestPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSOTAScheduleResponsePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSOTAScheduleRequestPayload_UpdateSource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSOTAScheduleRequestPayload_UpdateSchedule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSOTAScheduleRequestPayload_UpdateSchedule_SingleSchedule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSOTAScheduleRequestPayload_UpdateSchedule_RepeatedSchedule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_inbs_sb_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*INBMRequestPayload_PingRequest)(nil),
		(*INBMRequestPayload_SetSotaScheduleRequest)(nil),
	}
	file_inbs_sb_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*INBMResponsePayload_PingResponse)(nil),
		(*INBMResponsePayload_SetSotaScheduleResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inbs_sb_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inbs_sb_proto_goTypes,
		DependencyIndexes: file_inbs_sb_proto_depIdxs,
		EnumInfos:         file_inbs_sb_proto_enumTypes,
		MessageInfos:      file_inbs_sb_proto_msgTypes,
	}.Build()
	File_inbs_sb_proto = out.File
	file_inbs_sb_proto_rawDesc = nil
	file_inbs_sb_proto_goTypes = nil
	file_inbs_sb_proto_depIdxs = nil
}
