// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: inbs_sb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduledUpdateRequestPayload_UpdateType int32

const (
	ScheduledUpdateRequestPayload_SOTA ScheduledUpdateRequestPayload_UpdateType = 0 // Software Over The Air updates
)

// Enum value maps for ScheduledUpdateRequestPayload_UpdateType.
var (
	ScheduledUpdateRequestPayload_UpdateType_name = map[int32]string{
		0: "SOTA",
	}
	ScheduledUpdateRequestPayload_UpdateType_value = map[string]int32{
		"SOTA": 0,
	}
)

func (x ScheduledUpdateRequestPayload_UpdateType) Enum() *ScheduledUpdateRequestPayload_UpdateType {
	p := new(ScheduledUpdateRequestPayload_UpdateType)
	*p = x
	return p
}

func (x ScheduledUpdateRequestPayload_UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScheduledUpdateRequestPayload_UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_inbs_sb_proto_enumTypes[0].Descriptor()
}

func (ScheduledUpdateRequestPayload_UpdateType) Type() protoreflect.EnumType {
	return &file_inbs_sb_proto_enumTypes[0]
}

func (x ScheduledUpdateRequestPayload_UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScheduledUpdateRequestPayload_UpdateType.Descriptor instead.
func (ScheduledUpdateRequestPayload_UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{6, 0}
}

type INBMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string              `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload   *INBMRequestPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *INBMRequest) Reset() {
	*x = INBMRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *INBMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INBMRequest) ProtoMessage() {}

func (x *INBMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INBMRequest.ProtoReflect.Descriptor instead.
func (*INBMRequest) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{0}
}

func (x *INBMRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *INBMRequest) GetPayload() *INBMRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type INBMResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string               `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload   *INBMResponsePayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *INBMResponse) Reset() {
	*x = INBMResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *INBMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INBMResponse) ProtoMessage() {}

func (x *INBMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INBMResponse.ProtoReflect.Descriptor instead.
func (*INBMResponse) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{1}
}

func (x *INBMResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *INBMResponse) GetPayload() *INBMResponsePayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type INBMRequestPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*INBMRequestPayload_PingRequest
	//	*INBMRequestPayload_ScheduledUpdateRequest
	Payload isINBMRequestPayload_Payload `protobuf_oneof:"payload"`
}

func (x *INBMRequestPayload) Reset() {
	*x = INBMRequestPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *INBMRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INBMRequestPayload) ProtoMessage() {}

func (x *INBMRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INBMRequestPayload.ProtoReflect.Descriptor instead.
func (*INBMRequestPayload) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{2}
}

func (m *INBMRequestPayload) GetPayload() isINBMRequestPayload_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *INBMRequestPayload) GetPingRequest() *PingRequestPayload {
	if x, ok := x.GetPayload().(*INBMRequestPayload_PingRequest); ok {
		return x.PingRequest
	}
	return nil
}

func (x *INBMRequestPayload) GetScheduledUpdateRequest() *ScheduledUpdateRequestPayload {
	if x, ok := x.GetPayload().(*INBMRequestPayload_ScheduledUpdateRequest); ok {
		return x.ScheduledUpdateRequest
	}
	return nil
}

type isINBMRequestPayload_Payload interface {
	isINBMRequestPayload_Payload()
}

type INBMRequestPayload_PingRequest struct {
	PingRequest *PingRequestPayload `protobuf:"bytes,1,opt,name=ping_request,json=pingRequest,proto3,oneof"`
}

type INBMRequestPayload_ScheduledUpdateRequest struct {
	ScheduledUpdateRequest *ScheduledUpdateRequestPayload `protobuf:"bytes,2,opt,name=scheduled_update_request,json=scheduledUpdateRequest,proto3,oneof"`
}

func (*INBMRequestPayload_PingRequest) isINBMRequestPayload_Payload() {}

func (*INBMRequestPayload_ScheduledUpdateRequest) isINBMRequestPayload_Payload() {}

type INBMResponsePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*INBMResponsePayload_PingResponse
	//	*INBMResponsePayload_ScheduledUpdateResponse
	Payload isINBMResponsePayload_Payload `protobuf_oneof:"payload"`
}

func (x *INBMResponsePayload) Reset() {
	*x = INBMResponsePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *INBMResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INBMResponsePayload) ProtoMessage() {}

func (x *INBMResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INBMResponsePayload.ProtoReflect.Descriptor instead.
func (*INBMResponsePayload) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{3}
}

func (m *INBMResponsePayload) GetPayload() isINBMResponsePayload_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *INBMResponsePayload) GetPingResponse() *PingResponsePayload {
	if x, ok := x.GetPayload().(*INBMResponsePayload_PingResponse); ok {
		return x.PingResponse
	}
	return nil
}

func (x *INBMResponsePayload) GetScheduledUpdateResponse() *ScheduledUpdateResponsePayload {
	if x, ok := x.GetPayload().(*INBMResponsePayload_ScheduledUpdateResponse); ok {
		return x.ScheduledUpdateResponse
	}
	return nil
}

type isINBMResponsePayload_Payload interface {
	isINBMResponsePayload_Payload()
}

type INBMResponsePayload_PingResponse struct {
	PingResponse *PingResponsePayload `protobuf:"bytes,1,opt,name=ping_response,json=pingResponse,proto3,oneof"`
}

type INBMResponsePayload_ScheduledUpdateResponse struct {
	ScheduledUpdateResponse *ScheduledUpdateResponsePayload `protobuf:"bytes,2,opt,name=scheduled_update_response,json=scheduledUpdateResponse,proto3,oneof"`
}

func (*INBMResponsePayload_PingResponse) isINBMResponsePayload_Payload() {}

func (*INBMResponsePayload_ScheduledUpdateResponse) isINBMResponsePayload_Payload() {}

type PingRequestPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequestPayload) Reset() {
	*x = PingRequestPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequestPayload) ProtoMessage() {}

func (x *PingRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequestPayload.ProtoReflect.Descriptor instead.
func (*PingRequestPayload) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{4}
}

type PingResponsePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingResponsePayload) Reset() {
	*x = PingResponsePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponsePayload) ProtoMessage() {}

func (x *PingResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponsePayload.ProtoReflect.Descriptor instead.
func (*PingResponsePayload) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{5}
}

type ScheduledUpdateRequestPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdateType ScheduledUpdateRequestPayload_UpdateType `protobuf:"varint,1,opt,name=update_type,json=updateType,proto3,enum=inbs.ScheduledUpdateRequestPayload_UpdateType" json:"update_type,omitempty"`
	// Types that are assignable to Schedule:
	//	*ScheduledUpdateRequestPayload_EpochTime
	//	*ScheduledUpdateRequestPayload_Immediate
	Schedule isScheduledUpdateRequestPayload_Schedule `protobuf_oneof:"schedule"`
}

func (x *ScheduledUpdateRequestPayload) Reset() {
	*x = ScheduledUpdateRequestPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduledUpdateRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledUpdateRequestPayload) ProtoMessage() {}

func (x *ScheduledUpdateRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledUpdateRequestPayload.ProtoReflect.Descriptor instead.
func (*ScheduledUpdateRequestPayload) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{6}
}

func (x *ScheduledUpdateRequestPayload) GetUpdateType() ScheduledUpdateRequestPayload_UpdateType {
	if x != nil {
		return x.UpdateType
	}
	return ScheduledUpdateRequestPayload_SOTA
}

func (m *ScheduledUpdateRequestPayload) GetSchedule() isScheduledUpdateRequestPayload_Schedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

func (x *ScheduledUpdateRequestPayload) GetEpochTime() int64 {
	if x, ok := x.GetSchedule().(*ScheduledUpdateRequestPayload_EpochTime); ok {
		return x.EpochTime
	}
	return 0
}

func (x *ScheduledUpdateRequestPayload) GetImmediate() bool {
	if x, ok := x.GetSchedule().(*ScheduledUpdateRequestPayload_Immediate); ok {
		return x.Immediate
	}
	return false
}

type isScheduledUpdateRequestPayload_Schedule interface {
	isScheduledUpdateRequestPayload_Schedule()
}

type ScheduledUpdateRequestPayload_EpochTime struct {
	EpochTime int64 `protobuf:"varint,2,opt,name=epoch_time,json=epochTime,proto3,oneof"` // Scheduled time in UNIX epoch seconds
}

type ScheduledUpdateRequestPayload_Immediate struct {
	Immediate bool `protobuf:"varint,3,opt,name=immediate,proto3,oneof"` // For immediate updates
}

func (*ScheduledUpdateRequestPayload_EpochTime) isScheduledUpdateRequestPayload_Schedule() {}

func (*ScheduledUpdateRequestPayload_Immediate) isScheduledUpdateRequestPayload_Schedule() {}

type ScheduledUpdateResponsePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScheduledUpdateResponsePayload) Reset() {
	*x = ScheduledUpdateResponsePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inbs_sb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduledUpdateResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledUpdateResponsePayload) ProtoMessage() {}

func (x *ScheduledUpdateResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_inbs_sb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledUpdateResponsePayload.ProtoReflect.Descriptor instead.
func (*ScheduledUpdateResponsePayload) Descriptor() ([]byte, []int) {
	return file_inbs_sb_proto_rawDescGZIP(), []int{7}
}

var File_inbs_sb_proto protoreflect.FileDescriptor

var file_inbs_sb_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x6e, 0x62, 0x73, 0x5f, 0x73, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x69, 0x6e, 0x62, 0x73, 0x22, 0x60, 0x0a, 0x0b, 0x49, 0x4e, 0x42, 0x4d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x49, 0x4e, 0x42, 0x4d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x62, 0x0a, 0x0c, 0x49, 0x4e, 0x42, 0x4d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x49,
	0x4e, 0x42, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xbf, 0x01, 0x0a, 0x12,
	0x49, 0x4e, 0x42, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x3d, 0x0a, 0x0c, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x5f, 0x0a, 0x18, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x5f, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x16, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xc6, 0x01,
	0x0a, 0x13, 0x49, 0x4e, 0x42, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x40, 0x0a, 0x0d, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69,
	0x6e, 0x62, 0x73, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x70, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a, 0x19, 0x73, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x64, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x69, 0x6e, 0x62,
	0x73, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x48, 0x00, 0x52, 0x17, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x15, 0x0a, 0x13,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0xd5, 0x01, 0x0a, 0x1d, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x4f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e, 0x2e, 0x69, 0x6e, 0x62,
	0x73, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x09, 0x65, 0x70,
	0x6f, 0x63, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x09, 0x69, 0x6d, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x69, 0x6d,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x22, 0x16, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x4f, 0x54, 0x41, 0x10, 0x00, 0x42,
	0x0a, 0x0a, 0x08, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x22, 0x20, 0x0a, 0x1e, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0x49, 0x0a,
	0x0d, 0x49, 0x4e, 0x42, 0x53, 0x53, 0x42, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38,
	0x0a, 0x0b, 0x49, 0x4e, 0x42, 0x4d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x2e,
	0x69, 0x6e, 0x62, 0x73, 0x2e, 0x49, 0x4e, 0x42, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x1a, 0x11, 0x2e, 0x69, 0x6e, 0x62, 0x73, 0x2e, 0x49, 0x4e, 0x42, 0x4d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x28, 0x01, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inbs_sb_proto_rawDescOnce sync.Once
	file_inbs_sb_proto_rawDescData = file_inbs_sb_proto_rawDesc
)

func file_inbs_sb_proto_rawDescGZIP() []byte {
	file_inbs_sb_proto_rawDescOnce.Do(func() {
		file_inbs_sb_proto_rawDescData = protoimpl.X.CompressGZIP(file_inbs_sb_proto_rawDescData)
	})
	return file_inbs_sb_proto_rawDescData
}

var file_inbs_sb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inbs_sb_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_inbs_sb_proto_goTypes = []interface{}{
	(ScheduledUpdateRequestPayload_UpdateType)(0), // 0: inbs.ScheduledUpdateRequestPayload.UpdateType
	(*INBMRequest)(nil),                           // 1: inbs.INBMRequest
	(*INBMResponse)(nil),                          // 2: inbs.INBMResponse
	(*INBMRequestPayload)(nil),                    // 3: inbs.INBMRequestPayload
	(*INBMResponsePayload)(nil),                   // 4: inbs.INBMResponsePayload
	(*PingRequestPayload)(nil),                    // 5: inbs.PingRequestPayload
	(*PingResponsePayload)(nil),                   // 6: inbs.PingResponsePayload
	(*ScheduledUpdateRequestPayload)(nil),         // 7: inbs.ScheduledUpdateRequestPayload
	(*ScheduledUpdateResponsePayload)(nil),        // 8: inbs.ScheduledUpdateResponsePayload
}
var file_inbs_sb_proto_depIdxs = []int32{
	3, // 0: inbs.INBMRequest.payload:type_name -> inbs.INBMRequestPayload
	4, // 1: inbs.INBMResponse.payload:type_name -> inbs.INBMResponsePayload
	5, // 2: inbs.INBMRequestPayload.ping_request:type_name -> inbs.PingRequestPayload
	7, // 3: inbs.INBMRequestPayload.scheduled_update_request:type_name -> inbs.ScheduledUpdateRequestPayload
	6, // 4: inbs.INBMResponsePayload.ping_response:type_name -> inbs.PingResponsePayload
	8, // 5: inbs.INBMResponsePayload.scheduled_update_response:type_name -> inbs.ScheduledUpdateResponsePayload
	0, // 6: inbs.ScheduledUpdateRequestPayload.update_type:type_name -> inbs.ScheduledUpdateRequestPayload.UpdateType
	2, // 7: inbs.INBSSBService.INBMCommand:input_type -> inbs.INBMResponse
	1, // 8: inbs.INBSSBService.INBMCommand:output_type -> inbs.INBMRequest
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_inbs_sb_proto_init() }
func file_inbs_sb_proto_init() {
	if File_inbs_sb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inbs_sb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*INBMRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*INBMResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*INBMRequestPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*INBMResponsePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequestPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponsePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduledUpdateRequestPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inbs_sb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduledUpdateResponsePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_inbs_sb_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*INBMRequestPayload_PingRequest)(nil),
		(*INBMRequestPayload_ScheduledUpdateRequest)(nil),
	}
	file_inbs_sb_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*INBMResponsePayload_PingResponse)(nil),
		(*INBMResponsePayload_ScheduledUpdateResponse)(nil),
	}
	file_inbs_sb_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*ScheduledUpdateRequestPayload_EpochTime)(nil),
		(*ScheduledUpdateRequestPayload_Immediate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inbs_sb_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inbs_sb_proto_goTypes,
		DependencyIndexes: file_inbs_sb_proto_depIdxs,
		EnumInfos:         file_inbs_sb_proto_enumTypes,
		MessageInfos:      file_inbs_sb_proto_msgTypes,
	}.Build()
	File_inbs_sb_proto = out.File
	file_inbs_sb_proto_rawDesc = nil
	file_inbs_sb_proto_goTypes = nil
	file_inbs_sb_proto_depIdxs = nil
}
