# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import inbs_sb_pb2 as proto_dot_inbs__sb__pb2


class INBSServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.stream_stream(
                '/inbs.INBSService/Ping',
                request_serializer=proto_dot_inbs__sb__pb2.PingResponse.SerializeToString,
                response_deserializer=proto_dot_inbs__sb__pb2.PingRequest.FromString,
                )


class INBSServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request_iterator, context):
        """Bi-directional streaming method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_INBSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.stream_stream_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=proto_dot_inbs__sb__pb2.PingResponse.FromString,
                    response_serializer=proto_dot_inbs__sb__pb2.PingRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inbs.INBSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class INBSService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/inbs.INBSService/Ping',
            proto_dot_inbs__sb__pb2.PingResponse.SerializeToString,
            proto_dot_inbs__sb__pb2.PingRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
