#!/bin/bash

cat <<EOF
# dmidecode 3.0
Getting SMBIOS data from sysfs.
SMBIOS 2.6 present.

Handle 0x0000, DMI type 0, 24 bytes
BIOS Information
	Vendor: Intel Corp.
	Version: A..Y.B11.1
	Release Date: 10/13/2011
	Address: 0xF0000
	Runtime Size: 64 kB
	ROM Size: 4096 kB
	Characteristics:
		PCI is supported
		BIOS is upgradeable
		BIOS shadowing is allowed
		Boot from CD is supported
		Selectable boot is supported
		BIOS ROM is socketed
		EDD is supported
		5.25"/1.2 MB floppy services are supported (int 13h)
		3.5"/720 kB floppy services are supported (int 13h)
		3.5"/2.88 MB floppy services are supported (int 13h)
		Print screen service is supported (int 5h)
		8042 keyboard services are supported (int 9h)
		Serial services are supported (int 14h)
		Printer services are supported (int 17h)
		ACPI is supported
		USB legacy is supported
		BIOS boot specification is supported
		Targeted content distribution is supported

Handle 0x0026, DMI type 12, 5 bytes
System Configuration Options
        Option 1: To Be Filled By O.E.M.

Handle 0x0027, DMI type 13, 22 bytes
BIOS Language Information
        Language Description Format: Long
        Installable Languages: 1
                en|US|iso8859-1
        Currently Installed Language: en|US|iso8859-1

Handle 0x0037, DMI type 32, 20 bytes
System Boot Information
        Status: No errors detected

Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: testmanufacturer
	Product Name: Broxton P
	Version:
	Serial Number:
	UUID: 00F33C5D-93FC-E011-A7D5-3860778B8B9A
	Wake-up Type: Power Switch
	SKU Number: Not Specified
	Family: Not Specified
EOF
