#!/bin/bash

set -euxo pipefail

if uname -a | grep intel-core >&/dev/null ; then # EHL
	sleep 1
	systemctl start tpm2-abrmd
	umount /etc/intel-manageability/scratch 1>2 || true
	rm -rf /etc/intel-manageability/scratch 1>2
	mkdir -p /etc/intel-manageability/scratch 1>2
	mount -t ramfs -o size=32m ramfs /etc/intel-manageability/scratch 1>2
	chown root.root /etc/intel-manageability/scratch 1>2
	chmod og-rwx /etc/intel-manageability/scratch 1>2

	if ! (tpm2_unseal -c 0x81010001 >/dev/null) ; then
	    cd /etc/intel-manageability/scratch
	    tpm2_createprimary -Q -a o -o prim.ctx -G rsa:null:aes128cbc 1>2
	    dd if=/dev/urandom bs=1 count=32 2>/dev/null | tpm2_create -g sha256 -u seal.pub -r seal.priv -I- -C prim.ctx 1>2
	    tpm2_load -C prim.ctx -u seal.pub -r seal.priv -n seal.name -o seal.ctx 1>2
	    tpm2_evictcontrol -a o -c seal.ctx -p 0x81010001 1>2
	fi

	tpm2_unseal -c 0x81010001

	cd /
	umount /etc/intel-manageability/scratch 1>2
else # not EHL
	echo "generic passphrase"
fi
