# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloudadapter.pb.inbs.v1/inbs_sb.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cloudadapter.pb.common.v1 import common_pb2 as common_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15inbs/v1/inbs_sb.proto\x12\x07inbs.v1\x1a\x16\x63ommon/v1/common.proto\"Z\n\x0bINBMRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12,\n\x0cping_request\x18\x02 \x01(\x0b\x32\x14.inbs.v1.PingRequestH\x00\x42\t\n\x07payload\"]\n\x0cINBMResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12.\n\rping_response\x18\x02 \x01(\x0b\x32\x15.inbs.v1.PingResponseH\x00\x42\t\n\x07payload\"\r\n\x0bPingRequest\"\x0e\n\x0cPingResponse\"D\n\x10TestCommonImport\x12\x30\n\x0e\x63ommon_message\x18\x01 \x01(\x0b\x32\x18.common.v1.CommonMessage2O\n\rINBSSBService\x12>\n\x0bINBMCommand\x12\x15.inbs.v1.INBMResponse\x1a\x14.inbs.v1.INBMRequest(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inbs.v1.inbs_sb_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INBMREQUEST']._serialized_start=58
  _globals['_INBMREQUEST']._serialized_end=148
  _globals['_INBMRESPONSE']._serialized_start=150
  _globals['_INBMRESPONSE']._serialized_end=243
  _globals['_PINGREQUEST']._serialized_start=245
  _globals['_PINGREQUEST']._serialized_end=258
  _globals['_PINGRESPONSE']._serialized_start=260
  _globals['_PINGRESPONSE']._serialized_end=274
  _globals['_TESTCOMMONIMPORT']._serialized_start=276
  _globals['_TESTCOMMONIMPORT']._serialized_end=344
  _globals['_INBSSBSERVICE']._serialized_start=346
  _globals['_INBSSBSERVICE']._serialized_end=425
# @@protoc_insertion_point(module_scope)
