"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import cloudadapter.pb.common.v1.common_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class HandleINBMCommandRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    request_id: builtins.str
    @property
    def command(self) -> global___INBMCommand: ...
    def __init__(
        self,
        *,
        request_id: builtins.str = ...,
        command: global___INBMCommand | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["command", b"command"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["command", b"command", "request_id", b"request_id"]) -> None: ...

global___HandleINBMCommandRequest = HandleINBMCommandRequest

@typing_extensions.final
class HandleINBMCommandResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    request_id: builtins.str
    @property
    def error(self) -> cloudadapter.pb.common.v1.common_pb2.Error: ...
    def __init__(
        self,
        *,
        request_id: builtins.str = ...,
        error: cloudadapter.pb.common.v1.common_pb2.Error | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["error", b"error"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["error", b"error", "request_id", b"request_id"]) -> None: ...

global___HandleINBMCommandResponse = HandleINBMCommandResponse

@typing_extensions.final
class INBMCommand(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UPDATE_SCHEDULED_OPERATIONS_FIELD_NUMBER: builtins.int
    PING_FIELD_NUMBER: builtins.int
    @property
    def update_scheduled_operations(self) -> global___UpdateScheduledOperations: ...
    @property
    def ping(self) -> global___Ping: ...
    def __init__(
        self,
        *,
        update_scheduled_operations: global___UpdateScheduledOperations | None = ...,
        ping: global___Ping | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["inbm_command", b"inbm_command", "ping", b"ping", "update_scheduled_operations", b"update_scheduled_operations"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["inbm_command", b"inbm_command", "ping", b"ping", "update_scheduled_operations", b"update_scheduled_operations"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["inbm_command", b"inbm_command"]) -> typing_extensions.Literal["update_scheduled_operations", "ping"] | None: ...

global___INBMCommand = INBMCommand

@typing_extensions.final
class UpdateScheduledOperations(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCHEDULED_OPERATIONS_FIELD_NUMBER: builtins.int
    @property
    def scheduled_operations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[cloudadapter.pb.common.v1.common_pb2.ScheduledOperation]: ...
    def __init__(
        self,
        *,
        scheduled_operations: collections.abc.Iterable[cloudadapter.pb.common.v1.common_pb2.ScheduledOperation] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["scheduled_operations", b"scheduled_operations"]) -> None: ...

global___UpdateScheduledOperations = UpdateScheduledOperations

@typing_extensions.final
class Ping(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Ping = Ping
