"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import cloudadapter.pb.common.v1.common_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class HandleINBMCommandRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    request_id: builtins.str
    @property
    def command(self) -> global___INBMCommand: ...
    def __init__(
        self,
        *,
        request_id: builtins.str = ...,
        command: global___INBMCommand | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["command", b"command"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["command", b"command", "request_id", b"request_id"]) -> None: ...

global___HandleINBMCommandRequest = HandleINBMCommandRequest

@typing.final
class HandleINBMCommandResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    request_id: builtins.str
    @property
    def error(self) -> cloudadapter.pb.common.v1.common_pb2.Error: ...
    def __init__(
        self,
        *,
        request_id: builtins.str = ...,
        error: cloudadapter.pb.common.v1.common_pb2.Error | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["error", b"error"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "request_id", b"request_id"]) -> None: ...

global___HandleINBMCommandResponse = HandleINBMCommandResponse

@typing.final
class INBMCommand(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UPDATE_SCHEDULED_OPERATIONS_FIELD_NUMBER: builtins.int
    PING_FIELD_NUMBER: builtins.int
    @property
    def update_scheduled_operations(self) -> global___UpdateScheduledOperations: ...
    @property
    def ping(self) -> global___Ping: ...
    def __init__(
        self,
        *,
        update_scheduled_operations: global___UpdateScheduledOperations | None = ...,
        ping: global___Ping | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["inbm_command", b"inbm_command", "ping", b"ping", "update_scheduled_operations", b"update_scheduled_operations"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["inbm_command", b"inbm_command", "ping", b"ping", "update_scheduled_operations", b"update_scheduled_operations"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["inbm_command", b"inbm_command"]) -> typing.Literal["update_scheduled_operations", "ping"] | None: ...

global___INBMCommand = INBMCommand

@typing.final
class UpdateScheduledOperations(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCHEDULED_OPERATIONS_FIELD_NUMBER: builtins.int
    @property
    def scheduled_operations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[cloudadapter.pb.common.v1.common_pb2.ScheduledOperation]: ...
    def __init__(
        self,
        *,
        scheduled_operations: collections.abc.Iterable[cloudadapter.pb.common.v1.common_pb2.ScheduledOperation] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["scheduled_operations", b"scheduled_operations"]) -> None: ...

global___UpdateScheduledOperations = UpdateScheduledOperations

@typing.final
class Ping(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Ping = Ping

@typing.final
class SendNodeUpdateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    JOB_UPDATE_FIELD_NUMBER: builtins.int
    request_id: builtins.str
    node_id: builtins.str
    @property
    def job_update(self) -> cloudadapter.pb.common.v1.common_pb2.Job:
        """node_id will be filled in by INBS; schedule_id, executed_by, desired_start_time, create_time will be ignored"""

    def __init__(
        self,
        *,
        request_id: builtins.str = ...,
        node_id: builtins.str = ...,
        job_update: cloudadapter.pb.common.v1.common_pb2.Job | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["job_update", b"job_update", "update", b"update"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["job_update", b"job_update", "node_id", b"node_id", "request_id", b"request_id", "update", b"update"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["update", b"update"]) -> typing.Literal["job_update"] | None: ...

global___SendNodeUpdateRequest = SendNodeUpdateRequest

@typing.final
class SendNodeUpdateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    request_id: builtins.str
    @property
    def error(self) -> cloudadapter.pb.common.v1.common_pb2.Error: ...
    def __init__(
        self,
        *,
        request_id: builtins.str = ...,
        error: cloudadapter.pb.common.v1.common_pb2.Error | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["error", b"error"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "request_id", b"request_id"]) -> None: ...

global___SendNodeUpdateResponse = SendNodeUpdateResponse
