"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CommonMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HELLO_FIELD_NUMBER: builtins.int
    hello: builtins.str
    def __init__(
        self,
        *,
        hello: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["hello", b"hello"]) -> None: ...

global___CommonMessage = CommonMessage
