FROM golang:1.22 AS builder

WORKDIR /go/src/app
COPY inbm/trtl .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o trtl .

FROM python:3.12-slim

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
ARG http_proxy
ARG https_proxy
ARG no_proxy

ENV HTTP_PROXY=$HTTP_PROXY
ENV HTTPS_PROXY=$HTTPS_PROXY
ENV NO_PROXY=$NO_PROXY
ENV http_proxy=$http_proxy
ENV https_proxy=$https_proxy
ENV no_proxy=$no_proxy

# Install build essentials and Docker CLI
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list \
    && apt-get update \
    && apt-get install -y docker-ce-cli \
    && rm -rf /var/lib/apt/lists/*

COPY inbm/dispatcher-agent/requirements.txt /app/dispatcher-agent/requirements.txt
RUN pip config set global.proxy ${HTTP_PROXY} && \
    pip install --no-cache-dir -r /app/dispatcher-agent/requirements.txt

COPY inbm-lib /app/inbm-lib
RUN pip install --no-cache-dir -e /app/inbm-lib

COPY inbm/dispatcher-agent /app/dispatcher-agent
COPY inbm/dispatcher-agent/fpm-template /

COPY --from=builder /go/src/app/trtl /usr/bin/trtl

RUN mkdir -p /var/intel-manageability
RUN sed -i 's/level=ERROR/level=DEBUG/g' /etc/intel-manageability/public/dispatcher-agent/logging.ini

# used by INBM to detect if running in a container
ENV container=docker
ENV PYTHONPATH=/app:/app/dispatcher-agent:/app/inbm-lib
ENV MQTT_HOST=mosquitto
ENV MQTT_PORT=1883
ENV USE_TLS=False

WORKDIR /app/dispatcher-agent
CMD ["python", "-m", "dispatcher.dispatcher"]
