name: CODE REVIEW REPORT
on:
  issue_comment:
jobs:
  pr_agent_report:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ai-review') && (contains(github.event.comment.body, '/generate_report') && github.event.comment.user.login != 'nex-maximus') || (github.event_name == 'pull_request' && github.event.pull_request.user.login != 'nex-maximus') }}
    runs-on: ["ubuntu-latest"]
    container: 
      image: 011528261982.dkr.ecr.us-west-2.amazonaws.com/smartdevops:genai-stable
      options: --pull always
      credentials:
      # Make sure to add the AWS access key and secret key to github secrets vault
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: PR Agent report action step
        id: report
        run: |
          . /genai_agent/genai_env/bin/activate && /genai_agent/get_pr_eval_report.sh
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_ACTION.AUTO_REVIEW: true
          GITHUB_ACTION.AUTO_DESCRIBE: true
          GITHUB_ACTION.UPDATE_TITLE: false
          PR_NUMBER: ${{ github.event.number }}
          API_KEY: ${{ secrets.API_KEY }}
          API_BASE: ${{ secrets.API_BASE }}
          STABLE_API_VERSION: ${{ secrets.STABLE_API_VERSION }}
          PREVIEW_API_VERSION: ${{ secrets.PREVIEW_API_VERSION }}
          DEPLOY_NAME: ${{ secrets.DEPLOY_NAME }}
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
          # Below secrets to fetch the auth token for Intel's API gateway 
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}