name: ON-BOARDING-NEW-BRANCH
on: workflow_dispatch
permissions:
  contents: read
jobs:
  Checkout:
    runs-on: [self-hosted, maximus-unit-test-os]
    steps:
      - name: Checkout repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          fetch-depth: 0
          persist-credentials: false

  CREATE-PR:
    permissions:
      contents: write
      pull-requests: write
    needs: Checkout
    runs-on: [self-hosted, maximus-unit-test-os]
    name: Create GenAI Branch and PR
    steps:
      - id: maximus-create-pr-action
        run: |
          cd  ../../../genai_ut_gen
          cp /home/runner/scripts/.env .
          python create_pr.py
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
