name: UNIT-TEST-RUN-WORKFLOW-DISPATCH
on:
  workflow_dispatch
jobs:
  Checkout:
    if: startsWith(github.ref, 'refs/heads/NEX_MAXIMUS_UT/')
    runs-on: [self-hosted, maximus-unit-test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

  CREATE-USER-RUN-ENV:
    needs: Checkout
    runs-on: [self-hosted, maximus-unit-test]
    name: Create User Run Environment
    steps:
      - id: maximus-create-env-action
        uses: intel-innersource/frameworks.actions.maximus.genai-gpt/create-env@feature/genai_ut_eval_release
    env:
      # <Input relative filepath of your requirements.txt path i.e. dir-name/requirements.txt >
      REQUIREMENTS_PATH: requirements.txt

  UNIT-TEST-RUN:
    needs: CREATE-USER-RUN-ENV
    runs-on: [self-hosted, maximus-unit-test]
    name: Run Unit Tests
    steps:
      - id: genai-maximus-action
        uses: intel-innersource/frameworks.actions.maximus.genai-gpt/unit-test@feature/genai_ut_eval_release
    env:
      TASK_TYPE: run
      # INCLUDE_PATHS: <Include your paths here if want to run UT on specific files/dirs>
      # EXCLUDE_PATHS: <Exclude your paths here if want to exclude specific files/dirs>
